
sudo: required

language: c

compiler: gcc

notifications:
  email: false

cache:
  directories:
  - download-cache
  - perl5

env:
  global:
    - JOBS=2
    - LUAROCKS_VER=2.4.3
  matrix:
    - OPENRESTY_VER=1.15.8.2

install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev ssl-cert
  - mkdir -p download-cache
  - if [ ! -f download-cache/openresty-$OPENRESTY_VER.tar.gz ]; then wget -O download-cache/openresty-$OPENRESTY_VER.tar.gz http://openresty.org/download/openresty-$OPENRESTY_VER.tar.gz; fi
  - if [ ! -f download-cache/luarocks-$LUAROCKS_VER.tar.gz ]; then wget -O download-cache/luarocks-$LUAROCKS_VER.tar.gz https://luarocks.github.io/luarocks/releases/luarocks-$LUAROCKS_VER.tar.gz; fi
  - tar -zxf download-cache/openresty-$OPENRESTY_VER.tar.gz
  - tar -zxf download-cache/luarocks-$LUAROCKS_VER.tar.gz
  - pushd openresty-$OPENRESTY_VER
  - export OPENRESTY_PREFIX=$TRAVIS_BUILD_DIR/openresty-$OPENRESTY_VER
  - ./configure --prefix=$OPENRESTY_PREFIX -j$JOBS > build.log 2>&1 || (cat build.log && exit 1)
  - make -j$JOBS > build.log 2>&1 || (cat build.log && exit 1)
  - make install > build.log 2>&1 || (cat build.log && exit 1)
  - popd
  - pushd luarocks-$LUAROCKS_VER
  - export LUAROCKS_PREFIX=$TRAVIS_BUILD_DIR/luarocks-$LUAROCKS_VER
  - ./configure --with-lua=$OPENRESTY_PREFIX/luajit --with-lua-include=$OPENRESTY_PREFIX/luajit/include/luajit-2.1 --lua-suffix=jit
  - make build
  - sudo make install
  - popd
  - export PATH=$OPENRESTY_PREFIX/nginx/sbin:$OPENRESTY_PREFIX/bin:$OPENRESTY_PREFIX/luajit/bin:$LUAROCKS_PREFIX/bin:$PATH
  - sudo luarocks install luacheck > build.log 2>&1 || (cat build.log && exit 1)
  # install penlight manually because busted deps would install resty-incompatible Penlight 1.8.0
  - sudo luarocks install penlight 1.7.0 > build.log 2>&1 || (cat build.log && exit 1)
  - sudo luarocks install busted > build.log 2>&1 || (cat build.log && exit 1)
  - sudo luarocks make
  - export "LUA_PATH=$OPENRESTY_PREFIX/site/lualib/?.lua;$OPENRESTY_PREFIX/site/lualib/?/init.lua;$OPENRESTY_PREFIX/lualib/?.lua;$OPENRESTY_PREFIX/lualib/?/init.lua;;"
  - export "LUA_CPATH=$OPENRESTY_PREFIX/site/lualib/?.so;$OPENRESTY_PREFIX/lualib/?.so;;"
  - eval 'luarocks path'
  - luarocks --version
  - resty -v
  - luajit -v

script:
  - luacheck .
  - ./rbusted

