name: "Lua"

concurrency:
  # for PR's cancel the running task, if another commit is pushed
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  # build on PR and push-to-master. This works for short-lived branches, and saves
  # CPU cycles on duplicated tests.
  # For long-lived branches that diverge, you'll want to run on all pushes, not
  # just on push-to-master.
  pull_request: {}
  push:
    branches:
    - master

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        luaVersion:
        # - "5.1" not supported because of 'goto' usage, a 5.2 feature
        - "5.2"
        - "5.3"
        - "5.4"
        - "luajit-2.1.0-beta3"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@v4

    - name: dependencies
      run: |
        luarocks make
        luarocks install lua-cjson
        luarocks install busted

    - name: test
      run: |
        busted --lua=lua
